stages:
  - build
  - test

# -- build ------------------

.build: &build
  stage: build
  after_script:
    - ls -l dist/
  artifacts:
    expire_in: 3h
    paths:
      - dist

build:tarball:
  <<: *build
  image: python:3.6
  script:
    - python -m pip install setuptools
    - python setup.py sdist bdist_wheel

build:el7:
  <<: *build
  image: ligo/base:el7
  before_script:
    - yum install -yq
          rpm-build
          epel-rpm-macros
          python-rpm-macros
          python-setuptools
          python2-six
          pyOpenSSL
          lal-python
          python2-ligo-segments
          python2-pytest
          python2-mock
  script:
    - python setup.py sdist
    - rpmbuild -tb dist/gwdatafind*.tar.gz
    - mv -v ~/rpmbuild/RPMS/*/python*-gwdatafind-*.rpm dist/
    - rm -rf dist/*.tar.gz

.build:debian: &build_debian
  <<: *build
  before_script:
    - apt-get update -yqq
    - apt-get install -yq
          dpkg-dev
          debhelper
          dh-python
          python-all-dev
          python3-all-dev
          python-setuptools
          python3-setuptools
          python-six
          python3-six
          python-openssl
          python3-openssl
          lal-python
          lal-python3
          python-ligo-segments
          python3-ligo-segments
          python-pytest
          python3-pytest
          python-mock
  script:
    - pushd .
    - python setup.py sdist
    - version=$(python setup.py --version)
    - cd dist
    - tar -xf gwdatafind-${version}.tar.gz
    - cd gwdatafind-${version}
    - dpkg-buildpackage -us -uc -b
    - popd
    - rm -rf dist/gwdatafind*

build:debian:jessie:
  <<: *build_debian
  image: ligo/base:jessie

build:debian:stretch:
  <<: *build_debian
  image: ligo/base:stretch

# -- test -------------------

.test: &test
  stage: test
  image: python
  before_script:
    - python -m pip install .
  script:
    - py.test --pyargs gwdatafind
    - python -m gwdatafind --help

test:python2.7:
  <<: *test
  image: python:2.7

test:python3.6:
  <<: *test
  image: python:3.6
